In [1]:
import pandas as pd
from pandas import read_csv
import matplotlib.pyplot as plt

In [2]:
path = '/Users/mariabelenalberti/Documents/smart-meters-in-london'
filename = '/weather_hh.csv'

weather = read_csv(path+filename)

In [3]:
# Extract the month and year for ease of analysis
weather['timestmap']= pd.to_datetime(weather['timestamp'],format = '%d/%m/%Y %H:%M')
weather['year'] = pd.DatetimeIndex(weather['timestmap']).year
weather['month'] = pd.DatetimeIndex(weather['timestmap']).month
weather['Date'] = pd.to_datetime(weather.year.astype(str) + '-' + weather.month.astype(str))

In [4]:
del weather['year']
del weather['month']
del weather['timestamp']

In [5]:
weather_group_by = weather.groupby(['Date']).mean().reset_index()

In [6]:
weather_group_by

,Date,visibility,windBearing,temperature,dewPoint,pressure,apparentTemperature,windSpeed,humidity
0,2012-01-01,11.484866,215.395161,6.776707,3.705578,1021.070349,4.701922,4.373333,0.813750
1,2012-02-01,10.541695,210.794540,4.868534,1.270101,1029.737687,2.829899,3.442011,0.783851
2,2012-03-01,9.320403,191.595430,9.307433,4.746989,1027.735833,8.151828,2.933952,0.752702
3,2012-04-01,11.767042,195.333333,8.600569,4.313208,1004.090042,7.058597,3.869639,0.761111
4,2012-05-01,11.239247,172.459677,13.492755,8.731129,1016.458237,12.975108,3.591626,0.748750
5,2012-06-01,11.782236,175.886111,14.950514,10.520958,1011.236597,14.932403,4.497597,0.763806
6,2012-07-01,12.149395,211.517473,16.838038,12.081841,1013.620497,16.847809,3.354530,0.755712
7,2012-08-01,12.346277,204.461022,18.345605,13.218091,1014.395040,18.365000,3.470202,0.737083
8,2012-09-01,12.385764,231.766667,14.628125,9.410125,1015.020236,14.495736,3.625069,0.731931
9,2012-10-01,10.414046,172.587366,10.960981,8.459825,1010.080754,10.346371,3.638696,0.852836
10,2012-11-01,10.753417,214.480556,7.813611,5.615486,1009.557417,6.369903,3.564292,0.864153
11,2012-12-01,11.270874,227.638441,5.860148,3.718468,1008.341452,3.416371,4.289664,0.864194
12,2013-01-01,9.491331,192.655914,4.506828,2.299556,1013.818412,2.150417,3.867702,0.860296
13,2013-02-01,10.352083,163.016369,3.800536,0.116949,1017.790208,0.637857,4.103125,0.777500
14,2013-03-01,9.794866,106.799731,3.833871,-0.010108,1008.729718,0.733468,4.052890,0.770242
15,2013-04-01,11.610625,166.266667,8.625514,3.053847,1015.039375,6.994597,4.438375,0.700306
16,2013-05-01,11.887258,209.145161,11.656532,6.020820,1012.179677,11.043038,3.907218,0.705336
17,2013-06-01,12.291819,179.604167,15.102486,9.576403,1018.543727,15.023708,4.030861,0.709792
18,2013-07-01,12.869005,152.706989,20.039099,13.137527,1019.922634,20.075659,3.093051,0.668978
19,2013-08-01,12.450282,216.895161,18.502594,12.396815,1017.602878,18.547124,3.350054,0.699382
20,2013-09-01,10.794181,209.344444,14.796778,11.269278,1015.756457,14.705375,3.003694,0.806208
21,2013-10-01,10.756828,207.444892,13.342648,10.784207,1011.148952,13.004315,4.305336,0.850336
22,2013-11-01,10.978194,247.587500,7.586111,4.623681,1017.431194,5.892403,3.458014,0.820194
23,2013-12-01,10.823952,204.935484,7.223091,4.469462,1015.034973,5.357083,4.465968,0.830753

In [35]:
path = '/Users/mariabelenalberti/Documents/smart-meters-in-london/daily_dataset.csv/'
filename = 'daily_dataset.csv'

energy = read_csv(path+filename)

In [36]:
energy.head()

,LCLid,day,energy_median,energy_mean,energy_max,energy_count,energy_std,energy_sum,energy_min
0,MAC000131,2011-12-15,0.4850,0.432045,0.868,22,0.239146,9.505,0.072
1,MAC000131,2011-12-16,0.1415,0.296167,1.116,48,0.281471,14.216,0.031
2,MAC000131,2011-12-17,0.1015,0.189812,0.685,48,0.188405,9.111,0.064
3,MAC000131,2011-12-18,0.1140,0.218979,0.676,48,0.202919,10.511,0.065
4,MAC000131,2011-12-19,0.1910,0.325979,0.788,48,0.259205,15.647,0.066

In [37]:
del energy['energy_median']
del energy['energy_max']
del energy['energy_count']
del energy['energy_std']
del energy['energy_sum']
del energy['energy_min']

In [38]:
energy.head()

       LCLid         day  energy_mean
0  MAC000131  2011-12-15     0.432045
1  MAC000131  2011-12-16     0.296167
2  MAC000131  2011-12-17     0.189812
3  MAC000131  2011-12-18     0.218979
4  MAC000131  2011-12-19     0.325979

In [42]:
energy['day']= pd.to_datetime(energy['day'],format = '%Y-%m-%d')
energy['year'] = pd.DatetimeIndex(energy['day']).year
energy['month'] = pd.DatetimeIndex(energy['day']).month
energy['Date'] = pd.to_datetime(energy.year.astype(str) + '-' + energy.month.astype(str))

In [43]:
energy.head()

       LCLid        day  energy_mean  year  month       Date
0  MAC000131 2011-12-15     0.432045  2011     12 2011-12-01
1  MAC000131 2011-12-16     0.296167  2011     12 2011-12-01
2  MAC000131 2011-12-17     0.189812  2011     12 2011-12-01
3  MAC000131 2011-12-18     0.218979  2011     12 2011-12-01
4  MAC000131 2011-12-19     0.325979  2011     12 2011-12-01

In [47]:
energy_12_13 = energy[(energy['year'] == 2012) | (energy['year'] == 2013)]

In [49]:
energy_12_13.head()

        LCLid        day  energy_mean  year  month       Date
17  MAC000131 2012-01-01     0.256021  2012      1 2012-01-01
18  MAC000131 2012-01-02     0.252083  2012      1 2012-01-01
19  MAC000131 2012-01-03     0.235500  2012      1 2012-01-01
20  MAC000131 2012-01-04     0.216271  2012      1 2012-01-01
21  MAC000131 2012-01-05     0.331021  2012      1 2012-01-01

In [54]:
del energy_12_13['day']
del energy_12_13['month']
del energy_12_13['LCLid']
del energy_12_13['year']

In [55]:
energy_12_13.head()

    energy_mean       Date
17     0.256021 2012-01-01
18     0.252083 2012-01-01
19     0.235500 2012-01-01
20     0.216271 2012-01-01
21     0.331021 2012-01-01

In [56]:
energy_group = energy_12_13.groupby(['Date']).mean().reset_index()

In [58]:
energy_weather = pd.merge(weather_group_by,energy_group,on = 'Date',how = 'left')

In [59]:
energy_weather

,Date,visibility,windBearing,temperature,dewPoint,pressure,apparentTemperature,windSpeed,humidity,energy_mean
0,2012-01-01,11.484866,215.395161,6.776707,3.705578,1021.070349,4.701922,4.373333,0.813750,0.270916
1,2012-02-01,10.541695,210.794540,4.868534,1.270101,1029.737687,2.829899,3.442011,0.783851,0.281165
2,2012-03-01,9.320403,191.595430,9.307433,4.746989,1027.735833,8.151828,2.933952,0.752702,0.231747
3,2012-04-01,11.767042,195.333333,8.600569,4.313208,1004.090042,7.058597,3.869639,0.761111,0.217975
4,2012-05-01,11.239247,172.459677,13.492755,8.731129,1016.458237,12.975108,3.591626,0.748750,0.187007
5,2012-06-01,11.782236,175.886111,14.950514,10.520958,1011.236597,14.932403,4.497597,0.763806,0.178524
6,2012-07-01,12.149395,211.517473,16.838038,12.081841,1013.620497,16.847809,3.354530,0.755712,0.173248
7,2012-08-01,12.346277,204.461022,18.345605,13.218091,1014.395040,18.365000,3.470202,0.737083,0.168760
8,2012-09-01,12.385764,231.766667,14.628125,9.410125,1015.020236,14.495736,3.625069,0.731931,0.183000
9,2012-10-01,10.414046,172.587366,10.960981,8.459825,1010.080754,10.346371,3.638696,0.852836,0.212171
10,2012-11-01,10.753417,214.480556,7.813611,5.615486,1009.557417,6.369903,3.564292,0.864153,0.238759
11,2012-12-01,11.270874,227.638441,5.860148,3.718468,1008.341452,3.416371,4.289664,0.864194,0.259745
12,2013-01-01,9.491331,192.655914,4.506828,2.299556,1013.818412,2.150417,3.867702,0.860296,0.263370
13,2013-02-01,10.352083,163.016369,3.800536,0.116949,1017.790208,0.637857,4.103125,0.777500,0.258225
14,2013-03-01,9.794866,106.799731,3.833871,-0.010108,1008.729718,0.733468,4.052890,0.770242,0.252281
15,2013-04-01,11.610625,166.266667,8.625514,3.053847,1015.039375,6.994597,4.438375,0.700306,0.209746
16,2013-05-01,11.887258,209.145161,11.656532,6.020820,1012.179677,11.043038,3.907218,0.705336,0.185457
17,2013-06-01,12.291819,179.604167,15.102486,9.576403,1018.543727,15.023708,4.030861,0.709792,0.174000
18,2013-07-01,12.869005,152.706989,20.039099,13.137527,1019.922634,20.075659,3.093051,0.668978,0.167439
19,2013-08-01,12.450282,216.895161,18.502594,12.396815,1017.602878,18.547124,3.350054,0.699382,0.164071
20,2013-09-01,10.794181,209.344444,14.796778,11.269278,1015.756457,14.705375,3.003694,0.806208,0.182622
21,2013-10-01,10.756828,207.444892,13.342648,10.784207,1011.148952,13.004315,4.305336,0.850336,0.198080
22,2013-11-01,10.978194,247.587500,7.586111,4.623681,1017.431194,5.892403,3.458014,0.820194,0.230641
23,2013-12-01,10.823952,204.935484,7.223091,4.469462,1015.034973,5.357083,4.465968,0.830753,0.244074

In [64]:
corr = energy_weather.corr()
corr.style.background_gradient(cmap='RdBu_r')